---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kibana
  namespace: cluster-config
spec:
  chart:
    spec:
      chart: kibana
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kibana
        namespace: cluster-config
  install:
    createNamespace: true
  interval: 1h0m0s
  releaseName: kibana
  targetNamespace: kibana
  values:
    elasticsearch:
      hosts: 
        - elastic1
      port: "9200"
