---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kibana
  namespace: kibana
spec:
  releaseName: kibana
  chart:
    spec:
      chart: kibana
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "10.2.6"
  interval: 1h0m0s
  install:
    createNamespace: true
  values:
    elasticsearch:
      hosts: 
        - elastic1
      port: "9200"
