---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kibana
  namespace: cluster-config 
spec:
  releaseName: kibana
  targetNamespace: kibana
  chart:
    spec:
      chart: kibana
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: cluster-config
      version: "10.2.6"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    elasticsearch:
      hosts: 
        - elastic1
      port: "9200"
