apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kibana
spec:
  releaseName: kibana
  chart:
    spec:
      chart: kibana
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "10.2.6"
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    elasticsearch:
      hosts: 
        - elastic1
      port: "9200"
