apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kibana
  name: kibana-modifier
rules:
- apiGroups: [""]
  resources: ["services", "deployments", "pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
