apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kibana-modifier
  namespace: kibana
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kibana-modifier
subjects:
- kind: ServiceAccount
  name: flux
  namespace: kibana
